### ISSUE TITLE
What does it do?

### ISSUE THREAD

**Issue by ukmoose** [tlindener/node-red-contrib-fritzbox#1]
It would be good if you could include within the readme an explanation of what the node does and how to use it, without having to read the source code/install the node.

The readme gets picked up by both npmjs and flows.node-red.org

e.g http://flows.nodered.org/node/node-red-contrib-fritzbox

**Comment by tlindener** [comment]
Hi,
yes that's a valid point. I didn't have much time to work on my nodes. I started writing down some basics, I will update it with more details when I get the time.
